//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreIDEA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int ProductID { get; set; }
        public string Articul { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> UnitOfMeasurementID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public string Description { get; set; }
        public byte[] image { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual UnitOfMeasurements UnitOfMeasurements { get; set; }
    }
}
